eclipse-tracecompass/org.eclipse.tracecompass

API_POLICY.md, CONTRIBUTING.md
- doc: Fix typos in API_POLICY.md: Fixes #13
- doc: Fix links in CONTRIBUTING.md
- Fix link to coding style
- Point to CODE_OF_CONDUCT.md file in repository
=> Fix some typos in document

lttng/org.eclipse.tracecompass.lttng2.ust.core/plugin.xml
=> callstack.core: Add icon to new callstack analysis

doc/org.eclipse.tracecompass.doc.user/doc/User-Guide.mediawiki, doc/org.eclipse.tracecompass.rcp.doc.user/doc/User-Guide.mediawiki, rcp/org.eclipse.tracecompass.rcp.incubator.ui/plugin.xml, tmf/org.eclipse.tracecompass.tmf/p2.inf
=> incubator: Point update site to stable-9.3

releng/org.eclipse.tracecompass.target/baseline/tracecompass-baseline-9.3.0.target, releng/scripts/generate_api_baseline_unit_ids.sh
=> releng: Add Trace Compass 9.3.0 baseline

.github/workflows/ci-base.yml, .github/workflows/ci-core-tests-only.yml, .github/workflows/ci-long-ui-tests-only.yml, .github/workflows/ci-short-ui-tests-only.yml
This avoids duplication of workflow configurations.
=> Configure reusable workflows for continuous integration

tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/views/timegraph/BaseDataProviderTimeGraphView.java, tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/widgets/timegraph/model/TimeGraphEntry.java
=> tmf: Fix missing refresh due to stale sampling

releng/scripts/create-new-and-noteworthy.py
Fix to output markdown instead of mediawiki
Fix for removal of Change-Id from commit messages
Original copy taken from tracecompass.incubator
=> releng: Add and fix create-new-and-noteworthy.py

releng/org.eclipse.tracecompass.integration.core.tests/src/org/eclipse/tracecompass/integration/core/tests/dataproviders/DataProviderManagerTest.java, tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java
tmf: Add API to retrieve data provider factories from dp manager
tmf: Add APIs to add and remove data provider factories
=> Manage data provider factories

lttng/org.eclipse.tracecompass.lttng2.ust.core/src/org/eclipse/tracecompass/lttng2/ust/core/trace/LttngUstTrace.java
This passes the declared event types and environment to children traces.
=> Change LttngUstTrace to validate as a CTFValidationStatus

releng/org.eclipse.tracecompass.target/tracecompass-e4.34.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
=> releng: Update e4.34 and eStaging targets for 2024-12 RC2

releng/org.eclipse.tracecompass.target/tracecompass-e4.34.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
=> releng: Update e4.34 and eStaging targets to 2024-12 release

TraceCompass.setup, releng/org.eclipse.tracecompass.target/baseline/tracecompass-baseline-10.2.0.target
=> Add baseline and update OOMPH setup

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/provisional/tmf/core/model/events/TmfEventTableDataProvider.java
The returned string will be in form "file:line" instead of [file:line].
Trace Server clients will be able to use the string directly in that case. Lists are less common clients need to handle it separately.
[Changed] Return one callsite in TmfEventTableDataProvider if not a list
=> tmf: Return one callsite in TmfEventTableDataProvider if not a list

releng/org.eclipse.tracecompass.releng-site/category.xml
While investigating disabling ECF's SimRel contribution I discovered that tracecompass requires json and ECF is the only update site that provide json.
This only affects the content of the update site.
I have verified by building the update site locally that SimRel can aggregate without ECF's udpate site contribution.
(I needed to address Mylyn separately).
=> Add json to the category.xml

tmf/org.eclipse.tracecompass.tmf.core/META-INF/MANIFEST.MF, tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderCapabilities.java, tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderDescriptor.java, tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderCapabilities.java, tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java
Increment minor version of tmf.core
API analysis
N/A
=> tmf: Increment minor version of tmf.core

rcp/org.eclipse.tracecompass.rcp/staging/feature.xml, releng/org.eclipse.tracecompass.target/tracecompass-e4.36.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
releng: Update e4.36 and eStaging targets for 2025-06 M2
Build with 4.36 and staging targets.
N/A
=> releng: Update e4.36 and eStaging targets for 2025-06 M2

releng/org.eclipse.tracecompass.target/tracecompass-e4.36.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
releng: Update e4.36 and eStaging targets for 2025-06 M3
Build with e4.36 or staging target
N/A
=> releng: Update e4.36 and eStaging targets for 2025-06 M3

releng/org.eclipse.tracecompass.target/tracecompass-e4.36.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
releng: Update e4.36 and eStaging targets for 2025-06 RC1
Build with e4.36 or staging target.
N/A
=> releng: Update e4.36 and eStaging targets for 2025-06 RC1

releng/org.eclipse.tracecompass.target/tracecompass-e4.36.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
releng: Update e4.36 and eStaging targets to 2025-06 release
Build with e4.36 and staging targets
N/A
=> releng: Update e4.36 and eStaging targets to 2025-06 release

releng/org.eclipse.tracecompass.target/baseline/tracecompass-baseline-11.0.0.target
releng: Add Trace Compass 11.0.0 baseline
Set API baseline to tracecompass-baseline-11.0.0.target in Eclipse IDE
N/A
=> releng: Add Trace Compass 11.0.0 baseline

TraceCompass.setup
releng: Update OOMPH setup file for 11.0.0
Install with OOMPH
N/A
=> releng: Update OOMPH setup file for 11.0.0

pom.xml, rcp/org.eclipse.tracecompass.rcp/feature.xml, rcp/org.eclipse.tracecompass.rcp/legacy-e4.35/feature.xml
releng: Build with tracecompass-e4.36 target by default
Build with default target
N/A
=> releng: Build with tracecompass-e4.36 target by default

rcp/org.eclipse.tracecompass.rcp/staging/feature.xml, releng/org.eclipse.tracecompass.target/tracecompass-e4.37.target
releng: Add e4.37 and update eStaging targets for 2025-09 M2
Build with e4.37 or eStaging target, using the staging RCP feature.xml
N/A
=> releng: Add e4.37 and update eStaging targets for 2025-09 M2

releng/org.eclipse.tracecompass.target/tracecompass-e4.37.target, releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target
releng: Update e4.37 and eStaging targets for 2025-09 RC1
Build with tracecompass-e4.37 and eStaging targets
N/A
=> releng: Update e4.37 and eStaging targets for 2025-09 RC1

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/provisional/tmf/core/model/TableColumnDescriptor.java
tmf: Fix `@since` tags
Check no API errors in development environment
N/A
=> tmf: Fix @since tags

rcp/org.eclipse.tracecompass.rcp/staging/feature.xml, releng/org.eclipse.tracecompass.target/tracecompass-e4.38.target
releng: Add e4.38 and update eStaging targets for 2025-12 M1
Build with tracecompass-e4.38 target and staging/feature.xml
N/A
=> releng: Add e4.38 and update eStaging targets for 2025-12 M1
