eclipse-tracecompass/org.eclipse.tracecompass

.github/workflows/ci-base.yml
.github/workflows/ci-core-tests-only.yml
.github/workflows/ci-long-ui-tests-only.yml
.github/workflows/ci-short-ui-tests-only.yml
releng/org.eclipse.tracecompass.integration.swtbot.tests/src/org/eclipse/tracecompass/integration/swtbot/tests/projectexplorer/ProjectExplorerTracesFolderTest.java
tmf/org.eclipse.tracecompass.tmf.ui.swtbot.tests/src/org/eclipse/tracecompass/tmf/ui/swtbot/tests/viewers/events/TestRefreshTextTrace.java

Add 3 workflows for different test focus which run in parallel:
- ci-core-test-only.yml
- ci-long-ui-test-only.yml
- ci-short-ui-test-only.yml
Add a ci-base.yml for future configuration as reusable workflows. This
file needs to be merged before configuring the other ci workflows for
it.
Updating some SwtBot tests to fix flakiness.

Add workflows for continuous integration

---

lttng/org.eclipse.tracecompass.lttng2.kernel.ui.swtbot.tests/src/org/eclipse/tracecompass/lttng2/kernel/ui/swtbot/tests/ResourcesViewTest.java

Replace direct check for buttons to be enabled with a waitUntil() check.
The buttons might temporarily disabled and then re-enabled in a separated thread.
This should fix intermittent failures observed in continuous integration. 

swtbot: Make ResourcesViewTests.testShowMarkers() more robust

---

BUILDING.md
CONTRIBUTING.md
DEVELOPMENT_ENV_SETUP.md

Fix a couple of typos in the documentation as well as link issues.

doc: Fix typos in guide

---

tmf/org.eclipse.tracecompass.tmf.remote.ui.swtbot.tests/src/org/eclipse/tracecompass/tmf/remote/ui/swtbot/tests/fetch/FetchRemoteTracesTest.java

- Use SWTBotUtils for selecting the Traces folder
This utility is used in many other tests and it is more robust. It omits the suffix that indicates the number of traces in project.
- Make cancel test more robust:
The import dialog might close too fast and then the cancel button is not available anymore. This happens sometimes in CI. To make the test more robust detect that case and continue the test execution.
This should fix intermittent failures happening in CI.

swtbot: Make FetchRemoteTracesTest more robust

---

lttng/org.eclipse.tracecompass.lttng2.kernel.ui.swtbot.tests/src/org/eclipse/tracecompass/lttng2/kernel/ui/swtbot/tests/ControlFlowViewTest.java
lttng/org.eclipse.tracecompass.lttng2.kernel.ui.swtbot.tests/src/org/eclipse/tracecompass/lttng2/kernel/ui/swtbot/tests/KernelTimeGraphViewTestBase.java
lttng/org.eclipse.tracecompass.lttng2.kernel.ui.swtbot.tests/src/org/eclipse/tracecompass/lttng2/kernel/ui/swtbot/tests/ResourcesViewTest.java

Use timeGraphIsReadyCondition() to make sure that timegraph is populated before getting the content.
This should fix some intermittent failures in CI.

swtbot: Make testOpenCloseOpen() for CFV/RV more robust

---

tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/internal/tmf/ui/viewers/statistics/TmfStatisticsViewer.java

When one job is already scheduled, the previous logic did not create another job preventing subsequent selection from updating the UI in the statistics view. This commit always computes a new job and cancels the previous one if present.
[Fixed] Updating statistics now handles concurrent jobs correctly
[Change-Id: I14c99c6eac40def82338ca9341031951a4703db4](https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/206052)

tmf: Handle multiple jobs when updating statistics

---

API_POLICY.md
CONTRIBUTING.md
DEVELOPMENT_ENV_SETUP.md
README.md
doc/org.eclipse.tracecompass.doc.dev/doc/Developer-Guide.mediawiki

- Fix references to new Trace Compass wiki location
New location of wiki is: 
https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/wiki
Fix also linter warnings in corresponding Markdown files.
- doc: remove mediawiki tags from DEVELOPMENT_SETUP.md
Fixes #12

Fix references to new Trace Compass wiki location and doc updates

---

analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/src/org/eclipse/tracecompass/analysis/profiling/core/tests/FlameChartDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/src/org/eclipse/tracecompass/analysis/profiling/core/tests/flamegraph/AggregationTreeTest.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/stubs/org/eclipse/tracecompass/analysis/profiling/core/tests/stubs2/CallStackAnalysisStub.java

This patch adds arrow in the CallStackProviderStub to test the data provider. It also adds checks for arrows in the testFetchModel of the FlameChartDataProviderTest

callstack.core: Add arrows to flamechart test

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statistics/TmfStateStatistics.java

When requested times are below the start time of the state system when doing a query2d, it throws an error. This patch fixes that issue by replace with the start time when doing the query2d.
[Fixes] #18

tmf: Fix for times requested before start time

---

tmf/org.eclipse.tracecompass.tmf.core/META-INF/MANIFEST.MF
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/project/model/TmfTraceType.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/project/model/TmfOpenTraceHelper.java

This utility checks whether the parent or grandparent path of given path to a file is a valid directory trace. If it is a directory trace then return the parent or grandparent path.
[Added] TmfTraceType.checkAndUpdateTracePath() to check directory traces

tmf: Add utility to detect directory traces from trace path

---

tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/views/histogram/HistogramView.java

Fixes: #47 
This PR fixes an issue where histograms would be allowed to have a 1ns window span, which should not be possible.
Signed-off-by: Vlad Arama <vlad.arama@ericsson.com>

tmf: fix invalid 1ns histogram span

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statistics/TmfStateStatistics.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statistics/TmfStatisticsEventTypesModule.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statistics/TmfStatisticsTotalsModule.java

There are still two issues with the previous implementation:
- Having the duplicates of the start time in the TimeArrayCondition will slow down the execution of the binary search.
- When the query2d returned no intervals, an exception is thrown. This situation was never encountered because the previous version would add at least the end time or the start time but that would lead to an incorrect first bucket or last bucket
This patch was the one I lost. I modified it a bit to reduce the complexity of the queryHistogram method.

tmf: Fix statistics queries when there is no intervals

---

ctf/org.eclipse.tracecompass.tmf.ctf.ui.swtbot.tests/src/org/eclipse/tracecompass/tmf/ctf/ui/swtbot/tests/TestInvalidCtfTrace.java

The error dialog has 2 labels where one contains the error message. Check in both labels for the expected error message.

ctf.core.tests: Fix intermittent failing TestInvalidCtfTrace

---

lttng/org.eclipse.tracecompass.lttng2.kernel.ui.swtbot.tests/src/org/eclipse/tracecompass/lttng2/kernel/ui/swtbot/tests/HelpMessageTest.java

The info dialog has multiple labels where one contains the info message. Use the expected value to get the label with the expected info message.

kernel.ui.swtbot.tests: Fix intermittent failing HelpMessageTest

---

analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/META-INF/MANIFEST.MF
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/src/org/eclipse/tracecompass/analysis/profiling/core/tests/weighted/WeightedTreeGroupByTest.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/src/org/eclipse/tracecompass/analysis/profiling/core/tests/weighted/WeightedTreeSetTest.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/src/org/eclipse/tracecompass/analysis/profiling/core/tests/weighted/WeightedTreeTest.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/stubs/org/eclipse/tracecompass/analysis/profiling/core/tests/stubs/weighted/SimpleTree.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/stubs/org/eclipse/tracecompass/analysis/profiling/core/tests/stubs/weighted/SimpleWeightedTreeProvider.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/stubs/org/eclipse/tracecompass/analysis/profiling/core/tests/stubs/weighted/WeightedTreeProviderStub.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/stubs/org/eclipse/tracecompass/analysis/profiling/core/tests/stubs/weighted/WeightedTreeTestData.java
analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/stubs/org/eclipse/tracecompass/analysis/profiling/core/tests/stubs/weighted/package-info.java

Move weighted tree tests from incubator that were forgotten when porting callstack.

profiling.core: add weighted tree tests from incubator

---

analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/callgraph2/CallGraphAnalysis.java

This patch corrects an issue where when opening a trace or experiment with the flamegraph view opened, it would schedule that call graph analysis before the call stack analysis was completed. This would result in an incorrect callgraph analysis and the flamegraph view would not work.
This issue was solved by checking that the call stack analysis is completed before calculating the callgraph.
[Fixed] Intermittent error with the flamegraph analysis

profiling.core: verify that the source flamechart is completed

---

ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/event/types/SequenceDeclaration.java

Resolves #58
For a test trace that covers this, see https://github.com/eclipse-tracecompass/tracecompass-test-traces/pull/3
This fix works for me with the above trace. It is based on the proposed babeltrace 1.5 fix (https://bugs.lttng.org/attachments/596) under the original LTTng issue (https://bugs.lttng.org/issues/1412).
I think that this fix is not needed for arrays, because the metadata parser simply rejects arrays with a length of less than 1 (i.e., throws an exception).

ctf.core: Explicitly align to support 0-length sequences

---

lttng/org.eclipse.tracecompass.lttng2.kernel.core/META-INF/MANIFEST.MF
lttng/org.eclipse.tracecompass.lttng2.kernel.core/plugin.xml
lttng/org.eclipse.tracecompass.lttng2.kernel.core/src/org/eclipse/tracecompass/internal/lttng2/kernel/core/criticalpath/CriticalPathParameterProvider.java
lttng/org.eclipse.tracecompass.lttng2.kernel.ui/META-INF/MANIFEST.MF
lttng/org.eclipse.tracecompass.lttng2.kernel.ui/plugin.xml

With this it's possible to re-use it in the Trace Compass trace server.
[Changed] Move CriticalPathParameterProvider to lttng2.core

lttng2.kernel: Move CriticalPathParameterProvider to lttng2.core

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/StyleProperties.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/widgets/timegraph/widgets/TimeGraphControl.java

This is very useful to be able to identify markers by letters or more importantly by numbers to show sequences.
Successor to https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/128504

tmf.ui: add support for unicode character marker symbols

---

releng/dockerfiles/Dockerfile

Update the dockerfile because mvn is not up to date to build Trace Compass.

releng: update alpine to have latest mvn

---

tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/widgets/virtualtable/TmfVirtualTable.java

In TmfVirtualTable, we override Widget.addListener() to defer the listener to the Table child of the Composite.
In 4.32, Control.addMenuDetectListener() implementation changed from calling addListener() to calling the new protected method addTypedListener().
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1112
Since we can't override properly this new method (we can override it but the override implementation can't call the protected method on another Control), we must override addMenuDetectListener() instead.

tmf: Fix addMenuDetectListener() change of behavior in 4.32

---

tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/internal/tmf/ui/widgets/timegraph/TimeGraphRender.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/widgets/timegraph/widgets/TimeGraphControl.java

Implement a workaround so that the font height matches the requested pixel height, as the font height in points determined by calculation results in a larger font than expected.
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1193
With the font now matching the requested height, the workaround for the marker symbol text y-position can be removed.
With the font now matching the requested height, request a slightly larger (2px) font height for time graph name and labels, to improve readability. In both cases the text is centered using the actual rendered text height.

tmf: Fix font height in TimeGraphRender.setFontForHeight()

---

analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/kernel/KernelThreadInformationProvider.java

This avoids many TimeRangeExceptions and undefined behaviour. It is visible when a kernel trace partially overlaps a userspace trace with a new callstack. The behavour is now defined rather than crashing out with an exception.

linux.core: Make getStatusIntervalsForThreads handle out of range queries

---

ctf/org.eclipse.tracecompass.ctf.core.tests/src/org/eclipse/tracecompass/ctf/core/tests/types/IntegerDeclarationTest.java
ctf/org.eclipse.tracecompass.ctf.core/META-INF/MANIFEST.MF
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/event/types/IntegerDeclaration.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/event/metadata/tsdl/TypeAliasParser.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/event/metadata/tsdl/integer/IntegerDeclarationParser.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/utils/JsonMetadataStrings.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/utils/LEB128.java

Adding variable-length integer support according to [CTF2-SPEC-2.0]
Testing of this feature can be done using the following test-trace:
https://github.com/eclipse-tracecompass/tracecompass-test-traces/pull/8
[CTF2-SPEC-2.0]: https://diamon.org/ctf/#vl-int-fc
Signed-off-by: Vlad Arama <vlad.arama@ericsson.com>

ctf2: add varints support and testing

---

DEVELOPMENT_ENV_SETUP.md

- The link for incubator is not up to date.
- The instructions did not specify that the incubator target should be selected if building with the incubator.

doc: improve development setup instructions

---

ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/event/types/IntegerDeclaration.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/event/types/IntegerDefinition.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/event/types/IntegerRange.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/event/metadata/tsdl/integer/IntegerDeclarationParser.java
ctf/org.eclipse.tracecompass.tmf.ctf.core/src/org/eclipse/tracecompass/tmf/ctf/core/event/CtfTmfEventField.java

This PR adds support for formatters or `integer field class mappings` according to [CTF2-SPEC-2.0](https://diamon.org/ctf/#int-fc).
Testing of this feature can be done using the following test-trace: https://github.com/eclipse-tracecompass/tracecompass-test-traces/pull/9
Signed-off-by: Vlad Arama <vlad.arama@ericsson.com>

ctf: add support for mappings

---

rcp/org.eclipse.tracecompass.rcp/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.30/feature.xml
releng/org.eclipse.tracecompass.target/tracecompass-e4.30.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.31.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.32.target
releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target

Use older version of org.mozilla.javascript for compatibility with incubator EASE Scripting feature.
Fixes #116

releng: Downgrade org.mozilla.rhino to org.mozilla.javascript

---

ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/trace/CTFStreamInput.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/trace/CTFTrace.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/trace/ICTFPacketDescriptor.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/trace/CTFIndexFile.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/trace/StreamInputPacketIndexEntry.java
ctf/org.eclipse.tracecompass.tmf.ctf.core.tests/src/org/eclipse/tracecompass/tmf/ctf/core/tests/trace/CtfTmfTraceTest.java
ctf/org.eclipse.tracecompass.tmf.ctf.core/src/org/eclipse/tracecompass/tmf/ctf/core/trace/CtfTmfTrace.java

IDX files were added to help speed up trace indexing. This patch will load them. This patch should not affect the system performance, but might lay down some groundwork to improve streaming performance.
The index format is not yet part of the CTF standard, but is described here:
https://git.efficios.com/?p=babeltrace.git;a=blob;f=src/plugins/ctf/fs-src/lttng-index.hpp;h=36dc7cc934d46366aa12ebf7b13f239e8699eacb;hb=HEAD

ctf: support out of spec index files from LTTng

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/analysis/AnalysisManagerTest.java
tmf/org.eclipse.tracecompass.tmf.core/META-INF/MANIFEST.MF
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/TmfAnalysisManager.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/ITmfTrace.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/TmfTrace.java

With this API analysis modules can be added or removed through the analysis framework while trace is open.
[Added] API to refresh analysis modules of an ITmfTrace.

tmf: Allow TmfTrace to refresh it's analysis modules

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/statesystem/StateSystemAnalysisModuleTest.java
tmf/org.eclipse.tracecompass.tmf.core/META-INF/MANIFEST.MF
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/statesystem/TmfStateSystemAnalysisModule.java

- Implement method for TmfStateSystemAnalysisModule
- This allows to delete state systems from the analysis module.
If state system is open, it will close the state system files first
before deleting the file. Otherwise delete the file directly.
- Calling methods are responsible to re-trigger the analysis execution

tmf: Add interface to clear persistent data of analysis modules

---

analysis/org.eclipse.tracecompass.analysis.timing.core.tests/.classpath
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/META-INF/MANIFEST.MF
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/build.properties
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreAnalysisTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreDensityDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTableDataProviderExperimentTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTableDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/stubs/org/eclipse/tracecompass/analysis/timing/core/tests/stubs/segmentstore/StubSegmentStoreOnDiskProvider.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/stubs/org/eclipse/tracecompass/analysis/timing/core/tests/stubs/segmentstore/StubSegmentStoreProvider.java
analysis/org.eclipse.tracecompass.analysis.timing.core/META-INF/MANIFEST.MF
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/analysis/timing/core/segmentstore/AbstractSegmentStoreAnalysisModule.java

This PR contains 2 commits:
- Implement AbstractSegmentStoreAnalysisModule.clearPersistentData()
- This allows to delete on-disk segment store data file from the analysis module. If segment store is open, it will close the segment store file first before deleting the file. Otherwise delete the file directly.
- Calling methods are responsible to re-trigger the analysis execution
- This allows deleting on-disk segment store state while a trace is open
- timing.tests: Move SegmentStoreAnalysisTest to stubs directory

Implement interface to delete persistant data for segment store analysis (on-disk)

---

analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/AbstractSegmentStoreStatisticsDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTreeStatisticsDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/statistics/StubTreeStatisticsAnalysis.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/statistics/TreeStatisticsTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/analysis/timing/core/statistics/ITreeStatistics.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/analysis/timing/core/statistics/ITreeStatisticsAnalysis.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/analysis/timing/core/statistics/TreeStatistics.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/AbstractSegmentStoreStatisticsDataProvider.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreTreeStatisticsDataProvider.java

The SegmentStoreStatisticsDataProvider is limited to supporting only two layers of hierarchies in the statistics. This commit introduces a tree structure that extends the IStatistics interface, enabling the addition of more layers to the constructed entries.

Add tree structures to statistics to add more hierarchies

---

analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTableDataProviderExperimentTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTableDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreTableDataProvider.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/tmf/core/segment/Messages.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/tmf/core/segment/messages.properties
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/TmfStrings.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/segment/SegmentStartNsTimeAspect.java

This will allow time synchronization when selecting a row in the Theia/VsCode extension to the trace server.
Fixes #74
[Added] "Timestamp ns" column in SegmentStoreTableDataProvder

analysis: Add "Timestamp ns" column in SegmentStoreTableDataProvder

---

analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreStatisticsAspects.java

The statistics previously used default values like Double.MAX_VALUE and Double.MIN_VALUE for fields such as min and max, which were displayed when no elements were present in the statistics. This commit introduces a default value of null for situations where there are no elements in the statistics.
[Added] Default value for SegmentStoreStatisticsAspects

Add default values to SegmentStoreStatisticsAspects

---

analysis/org.eclipse.tracecompass.analysis.counters.core/src/org/eclipse/tracecompass/analysis/counters/core/aspects/ITmfCounterAspect.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/event/aspect/LinuxPidAspect.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/event/aspect/LinuxTidAspect.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/event/aspect/ThreadPriorityAspect.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/internal/analysis/os/linux/core/latency/SystemCallLatencyAnalysis.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/internal/analysis/os/linux/core/swslatency/SWSLatencyAnalysis.java
analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/instrumented/FunctionTidAspect.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreTableDataProvider.java
lttng/org.eclipse.tracecompass.lttng2.ust.core/src/org/eclipse/tracecompass/internal/lttng2/ust/core/analysis/memory/UstMemoryAnalysisModule.java
tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/event/TmfEventTableDataProviderTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/tree/TmfTreeModelTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/trace/TmfTraceUtilsTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/stubs/org/eclipse/tracecompass/tmf/tests/stubs/model/tree/TmfTreeDataModelStub.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/provisional/tmf/core/model/events/TmfEventTableColumnDataModel.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/provisional/tmf/core/model/events/TmfEventTableDataProvider.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/event/aspect/ITmfEventAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/event/aspect/MultiAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/event/aspect/TmfBaseAspects.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/event/aspect/TmfCpuAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/event/aspect/TmfDeviceAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/tree/ITmfTreeDataModel.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/tree/TmfTreeDataModel.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/segment/ISegmentAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/segment/SegmentDurationAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/segment/SegmentEndTimeAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/segment/SegmentStartNsTimeAspect.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/segment/SegmentStartTimeAspect.java

Added data type to the event and segment aspects (Segment already had getType, but the aspects didn't). The aim was to synchronize the trace-server functionalities w.r.t. tables in order to indicate the type of columns.

Event aspect data type

---

statesystem/org.eclipse.tracecompass.statesystem.core/src/org/eclipse/tracecompass/internal/statesystem/core/backend/historytree/HistoryTreeBackendIterator.java

In HistoryBackEndIterator, do not reduce the time range condition for queuing children nodes when the current node is the root node, as its time range is not finalized during construction.
Fixes #156
[Fixed] Do not reduce time range condition for root nodes

statesystem: Do not reduce time range condition for root nodes

---

statesystem/org.eclipse.tracecompass.statesystem.core/src/org/eclipse/tracecompass/internal/statesystem/core/backend/historytree/ThreadedHistoryTreeBackend.java

The new API for query2D with reverse parameter is implemented in ThreadedHistoryTreeBackend. This avoids the base class implementation from being used, which is missing queued intervals.
Fixes #158
[Fixed] Implement new query2D API in ThreadedHistoryTreeBackend\

statesystem: Implement new query2D API in ThreadedHistoryTreeBackend

---

ctf/org.eclipse.tracecompass.ctf.core.tests/src/org/eclipse/tracecompass/ctf/core/tests/trace/MetadataTest.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/trace/CTFTrace.java
ctf/org.eclipse.tracecompass.tmf.ctf.core.tests/src/org/eclipse/tracecompass/tmf/ctf/core/tests/trace/CtfTmfTraceTest.java
ctf/org.eclipse.tracecompass.tmf.ctf.core/src/org/eclipse/tracecompass/tmf/ctf/core/trace/CtfTmfTrace.java

There is the need to get clock scale of the trace.
This commit added the clock scale to the environment variables of the trace.
[Added] clock scale in getEnvironment() in CTFTrace
[Changed] moved clock offset into getEnvironment() in CTFTrace
[Deprecated] CtfTmfTrace.CLOCK_OFFSET, use CTFTrace.CLOCK_OFFSET instead.
Signed-off-by: Siwei Zhang <siwei.zhang@ericsson.com>

Expose the clock properties in CTFTrace

---

analysis/org.eclipse.tracecompass.analysis.profiling.core.tests/src/org/eclipse/tracecompass/analysis/profiling/core/tests/FlameChartDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/instrumented/FlameChartDataProviderFactory.java
analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/instrumented/messages.properties
releng/org.eclipse.tracecompass.integration.core.tests/src/org/eclipse/tracecompass/integration/core/tests/dataproviders/DataProviderManagerTest.java

Prepend the analysis name before the view type, e.g. "Function Graph - Flame Chart". This to be consistent with other data providers that have common analysis (e.g. Function Graph - Latency Statistics)
This helps also with the default grouping by name of data providers in the trace server front-end.
[Changed] DP name of Flame Chart created by different analyses

profiling: Change DP name of Flame Charts created by different analyses

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/config/TmfConfigurationSourceTypeTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSourceType.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/TmfConfigurationSourceType.java

For schema specification see https://json-schema.org/
[Added] support for json-schema file to TmfConfigurationSourceType
See https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/103

tmf: Add support for json-schema file to TmfConfigurationSourceType

---

analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTableDataProviderExperimentTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/SegmentStoreTableDataProviderTest.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/src/org/eclipse/tracecompass/analysis/timing/core/tests/segmentstore/statistics/StubSegmentStatisticsAnalysis.java
analysis/org.eclipse.tracecompass.analysis.timing.core.tests/stubs/org/eclipse/tracecompass/analysis/timing/core/tests/stubs/segmentstore/StubSegmentStoreProvider.java
tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/trace/TmfTraceTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/stubs/org/eclipse/tracecompass/tmf/tests/stubs/analysis/TestAnalysis2.java
tmf/org.eclipse.tracecompass.tmf.core.tests/stubs/org/eclipse/tracecompass/tmf/tests/stubs/trace/TmfExperimentStub.java
tmf/org.eclipse.tracecompass.tmf.core.tests/stubs/org/eclipse/tracecompass/tmf/tests/stubs/trace/xml/TmfXmlTraceStub.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/ITmfTrace.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/TmfTrace.java

Many analysis utilities require analysis modules to be present in the ITmfTrace.getAnalysisModules() collection. This one is filled using the TMF analysis framework (see IAnalysisModuleSource implementation). The analysis framework will populate available IAnalysisModuesHelpers at startup (plug-in defined) or when a refresh is requested (XML analysis). For that a central storage for the modules configuration needs to be available to be parsed which are available for all ITmfTrace extensions. If a trace is opened a ITmfTrace instance is created and the applicable analysis module is instantiated and stored inside the ITmfTrace object.
Right now it's not possible to update available analysis module helpers in the TMF analysis framework based on a configuration specific for a trace instance. …

tmf: Add API to add and remove analysis modules to/from ITmfTrace

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/DataProviderDescriptorTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderDescriptor.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java

This will allow to show configuration parameters that were used to create a data provider to the user, as well as, group data providers using the parent ID.
[Added] parent ID and creation configuration to IDataProviderDescriptor
Bernd Hufmann <bernd.hufmann@ericsson.com>

tmf: Add parent ID and creation configuration to IDataProviderDescriptor

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfDataProviderConfigurator.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderParameterUtils.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderFactory.java

Add interface to implement to prepare a derived data provider with input parameter defined by ITmfConfigurationSourceType.
For that add interfaces ITmfDataProviderConfigurator for capabilities to create data providers that a data provider factory could implement.
Add getAdapter() interface to IDataProviderFactory to allow retrieving ITmfDataProviderConfigurator.
Example:
ITmfDataProviderConfigurator configurator =
factory.getAdapter(ITmfDataProviderConfigurator.class);
[Added] ITmfDataProviderConfigurator interface for custom data provider
[Added] getAdapter() interface to IDataProviderFactory
For example, to get a ITmfDataProviderSource implementation do:
```java
ITmfDataProviderSource source = factory.getAdapter(IDataProviderSource.class);
```
Note that this PR includes changes of other …

tmf: add ITmfDataProviderConfigurator interface for custom data provider

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/analysis/AnalysisModuleTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/stubs/org/eclipse/tracecompass/tmf/tests/stubs/analysis/TestConfigurableAnalysis.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java

This is meant to be used when creating and managing analysis modules programmatically and not through the TMF Analysis Framework (e.g. defining the analysis in the plug-in.xml). The configuration has to be  set before the analysis is scheduled, which is not supported by the TMF Analysis Framework.
This is useful in the trace server context for configurable analysis.
[Added] configuration setter/getter to IAnalysisModule

tmf: Add configuration setter/getter in IAnalysisModule

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/config/TmfConfigurationTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/TmfConfiguration.java

Also, generate unique UUID as ID from name.
[Added] Allow TmfConfiguration to be de-/serialized with GSON 
[Added] TmfConfiguration.UNKNOWN string if values are not set [Added[ Utility methods to write/read configuration to/from JSON file
Continued from #115

tmf: Allow TmfConfiguration to be de-/serialized with GSON

---

tmf/org.eclipse.tracecompass.tmf.analysis.xml.core.tests/src/org/eclipse/tracecompass/tmf/analysis/xml/core/tests/config/XmlConfigurationSourceTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSource.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfDataProviderConfigurator.java

- Add new API and default implementation of create and update methods in ITmfConfigurationSource.
- Change create method of ITmfDataProviderConfigurator. It has not been released and can be changed.
This is as alternative to Map<String, Object>.
[Added] ITmfConfiguration configuration create and update methods

tmf: Use ITmfConfiguration configuration create and update methods

---

releng/org.eclipse.tracecompass.testing/feature.xml

Commit e12b98a made o.e.tc.datastore.core.tests a plug-in instead of a fragment. It needs to be part of the testing feature so that downstream test plug-ins can successfully build.

testing: add o.e.tc.datastore.core.tests to testing feature

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderParameterUtils.java

No need to add APIs if not needed.

Remove recently added unused constant in DataProviderParameterUtils

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderDescriptor.java

This provider type can be used for grouping purposes as well as to have an entity to trigger configurations in the trace server front-ends.
[Added] data provider ProviderType.NONE for DPs without graphs
Bernd Hufmann <bernd.hufmann@ericsson.com>

tmf: Add data provider ProviderType.NONE for DPs without graphs

---

analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/instrumented/FlameChartDataProviderFactory.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentNameSegmentStoreStatisticsDataProviderFactory.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreScatterDataProviderFactory.java
analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreTableDataProviderFactory.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java

If a latency analysis was configured using an ITmfConfiguration instance, then set the configuration and parent ID in the Data Provider Descriptors of the corresponding data providers that being spawn by the Latency Analysis (e.g. Latency Statistics, Scatter Chart, Table and Flame Chart). This can be used for to show this information to end users of the trace server front-ends and for grouping of data providers in the front-end implementations.
- analysis: Set creation configuration to Latency Analysis DataProviderDescriptors
- timing: Use analysis id as parent ID for latency data providers with configurations. 
[Updated] Latency Analysis DataProviderDescriptors with config
[Updated] Latency Analysis DataProviderDescriptors with parentId
Signed-off-by: Bernd Hufmann …

timing: set parentId and creation configuration in DataProviderDescriptor for Latency Analysis with conifgurations

---

analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreScatterDataProvider.java

For example, if a trace doesn't have any call stack events to populate the segment store and hence populate the view, the data provider should return an empty model instead of failed for fetchTree and fetchXY.
[Fixed] Fix SegmentStoreScatterDataProvider for empty segment store
Note: This is bug is only visible when using the trace server and JS front-end and not in Eclipse.

timing: Fix SegmentStoreScatterDataProvider for empty segment store

---

analysis/org.eclipse.tracecompass.analysis.os.linux.core.tests/src/org/eclipse/tracecompass/analysis/os/linux/core/tests/inputoutput/AbstractTestInputOutput.java
analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/instrumented/FlameChartDataProviderFactory.java
releng/org.eclipse.tracecompass.integration.swtbot.tests/src/org/eclipse/tracecompass/integration/swtbot/tests/markers/MarkerSetSwtBotTest.java
tmf/org.eclipse.tracecompass.tmf.analysis.xml.ui/src/org/eclipse/tracecompass/internal/tmf/analysis/xml/ui/views/xychart/XmlXYView.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/tmf/core/statesystem/backends/partial/PartialHistoryBackend.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/experiment/TmfExperiment.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/internal/tmf/ui/project/wizards/tracepkg/importexport/ImportTracePackageWizardPage.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/project/model/TmfAnalysisElement.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/viewers/events/TmfEventsCache.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/viewers/xychart/XYChartLegendImageProvider.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/viewers/xychart/linechart/TmfCommonXAxisChartViewer.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/views/timegraph/TimeGraphFindDialog.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/views/uml2sd/SDWidget.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/views/uml2sd/ScrollView.java
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/views/uml2sd/core/Frame.java

This patch remove some casts that are showing as errors in eclipse.
I found two categories:
- Cast from children classes to parent classes: I removed those ones since they are not really needed.
- Cast after an instanceof check: It seems that in some recent version, the behaviour changed and these ones are sometimes classified as unnecessary. I found information on JEP 305 where that allows the following:
```java
if (animal instanceof Cat cat)  {  
out.println(cat.meow());  
}
```
However, in this case the following code indicates the cast as unnecessary:
```java
IResource resource = getResource();
if (resource instanceof IFolder) {
path = ((IFolder) resource).getFullPath();
}
```
IResource being a parent class of IFolder.
As I am not sure what really happens there, I have not made the …

tmf: remove unnecessary cast

---

analysis/org.eclipse.tracecompass.analysis.os.linux.core/META-INF/MANIFEST.MF
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/event/aspect/Messages.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/event/aspect/messages.properties
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/analysis/os/linux/core/model/OsStrings.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/internal/analysis/os/linux/core/threadstatus/ThreadEntryModel.java
analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/internal/analysis/os/linux/core/threadstatus/ThreadStatusDataProvider.java

Do not merge until https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/1149 is fixed.

linux: support columns in ThreadStatusDataProvider tree model

---

TraceCompass.setup
pom.xml
rcp/org.eclipse.tracecompass.rcp/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.32/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.33/feature.xml
releng/org.eclipse.tracecompass.target/baseline/tracecompass-baseline-10.2.0.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.34.target
releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target

- releng: Update e4.34 and eStaging targets to 2024-12 release
- releng: Add Trace Compass 10.2.0 baseline
- releng: Update OOMPH setup file for 10.2.0
- releng: Build with tracecompass-e4.34 target by default

Post 10.2 release master activities

---

lttng/org.eclipse.tracecompass.lttng2.control.ui.tests/src/org/eclipse/tracecompass/lttng2/control/ui/tests/service/LTTngControlServiceMiTest.java
lttng/org.eclipse.tracecompass.lttng2.control.ui.tests/src/org/eclipse/tracecompass/lttng2/control/ui/tests/service/LTTngControlServiceTest.java
lttng/org.eclipse.tracecompass.lttng2.control.ui.tests/testfiles/LTTngServiceMi3Test.cfg
lttng/org.eclipse.tracecompass.lttng2.control.ui.tests/testfiles/LTTngServiceMi3TestLTTng211.cfg
lttng/org.eclipse.tracecompass.lttng2.control.ui.tests/testfiles/LTTngServiceMiTest.cfg
lttng/org.eclipse.tracecompass.lttng2.control.ui/src/org/eclipse/tracecompass/internal/lttng2/control/ui/views/service/LTTngControlServiceConstants.java
lttng/org.eclipse.tracecompass.lttng2.control.ui/src/org/eclipse/tracecompass/internal/lttng2/control/ui/views/service/LTTngControlServiceMI.java

Don't fail if logger agents are not available (e.g. JUL).
[Fixed] listing UST domains if there are no logger agents
Fixes #192

lttng.control: Fix listing UST domains if there are no logger agents

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/tmf/core/histogram/HistogramDataProvider.java

For the event statistics histogram view, the HistogramDataProvider will occasionally fail with an IndexOutOfBoundsException when its fetchXY method is called before its state-system backed statistics have been populated with attributes.
Add a check to verify that the y-values provided by the statistics is large enough for the x-values.
The stacktrace in question. I occasionally see it when I open traces in vscode using the incubator trace-server.
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
at java.base/java.util.Arrays.setAll(Arrays.java:5414)
at org.eclipse.tracecompass.internal.tmf.core.histogram.HistogramDataProvider.fetchXY(HistogramDataProvider.java:131)
at …
```

tmf: Fix HistogramDataProvider index OOB

---

analysis/org.eclipse.tracecompass.analysis.profiling.core/src/org/eclipse/tracecompass/internal/analysis/profiling/core/instrumented/InstrumentedCallStackElement.java

To resolve symbols, the method retrieveSymbolKeyAt will query a symbol key attribute for every interval in a query2d. This creates a significant overhead that can easily be avoided if we cache this interval. For all current use cases, the symbol key interval is unique for each trace.

profiling: cache symbol key interval

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/DataProviderCapabilitiesTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/DataProviderDescriptorTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderCapabilities.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderDescriptor.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderCapabilities.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/DataProviderDescriptor.java

With this a data provider factory instance can advertise special capabilities that can be applied for the given data provider.
This commit adds code for that and implements the "canCreate" and "canDelete" capability. "canCreate" indicates that this instance can create a derived data provider. Use the IDataProviderFactory method getAdapter(ITmfDataProviderConfigurator) to obtains a ITmfDataProviderConfigurator. This interface has methods to get List<ITmfConfigurationSourceType> describing the parameters needed to create a derived data provider using method createDataProvider.
"canDelete" indicates a the data provider can be deleted using the method ITmfDataProviderConfigurator#deleteDataProviderDescriptor.
[Added] capabilities data structure to IDataProviderDescriptor
see also …

tmf: add capabilities data structure to IDataProviderDescriptor

---

.github/workflows/ci-base.yml
releng/org.eclipse.tracecompass.releng-site/legacy/category.xml

Add a legacy category.xml file for support of older targets
For example, 2021-06/e4.20 needs a different category.xml file due different name of json plugin.
Run build for 2021-06/e4.20 target in repo (use Java 17):
```sh
cp -f rcp/org.eclipse.tracecompass.rcp.product/legacy/tracing.product rcp/org.eclipse.tracecompass.rcp.product/
cp -f releng/org.eclipse.tracecompass.slf4j.binding.simple.properties/legacy/MANIFEST.MF releng/org.eclipse.tracecompass.slf4j.binding.simple.properties/META-INF
cp -f rcp/org.eclipse.tracecompass.rcp/legacy/feature.xml rcp/org.eclipse.tracecompass.rcp/
cp -f releng/org.eclipse.tracecompass.releng-site/legacy/category.xml releng/org.eclipse.tracecompass.releng-site/
mvn clean install -Dtarget-platform=tracecompass-e4.20 -Djdk.version=11 -Djdk.release=11 …
```

releng: Add a legacy category.xml file for support of older targets

---

pom.xml
rcp/org.eclipse.tracecompass.rcp.product/tracing.product
releng/org.eclipse.tracecompass.target/tracecompass-e4.20.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.21.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.22.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.23.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.24.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.25.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.26.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.27.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.28.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.29.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.30.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.31.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.32.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.33.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.34.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.35.target
releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target

Bundle [JustJ JVM](https://eclipse.dev/justj/) inside the Trace Compass RCP packages. 
Update target files to include JustJ JREs with respective version for that release. Use latest available JRE version for respective major version.
This will make it easier for end-users to use Trace Compass because Java doesn't need to be installed separately and it will include the correct, required version. 
**Notes**: 
- The stripped version of the JRE is used with debug information stripped and excluding the src.jar with sources used only for debugging. This minimizes the size of the JRE package because it's less than 1/2 the size of the corresponding full version.  If you'd like to debug the RCP (e.g. using remote debugging), use a separated JVM as described below.
- To run the RCP with a different …

releng: Bundle java runtime in Trace Compass RCP product packages

---

rcp/org.eclipse.tracecompass.rcp.product/legacy-e4.23-e4.25/tracing.product
rcp/org.eclipse.tracecompass.rcp.product/legacy-e4.26-e4.29/tracing.product
rcp/org.eclipse.tracecompass.rcp.product/legacy/tracing.product
rcp/org.eclipse.tracecompass.rcp/legacy-e4.30/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.32/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.33/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy/feature.xml
releng/org.eclipse.tracecompass.releng-site/legacy/category.xml

Add trace-event-logger plug-in to legacy feature.xml files
Add JustJ feature to legacy tracing.product files
Add trace-event-logger bundle to legacy releng-site category.xml file
Build with older targets.
N/A

releng: Fix legacy files for trace-event-logger and JustJ

---

analysis/org.eclipse.tracecompass.analysis.timing.core/src/org/eclipse/tracecompass/internal/analysis/timing/core/segmentstore/SegmentStoreTableDataProvider.java

Set the size of the segment store even if the provider doesn't implement `IAnalysisModule`. This change was made to support cases where `SegmentStoreTableDataProvider` is used with classes that do not implement `IAnalysisModule`.
Before this change:
Only analysis modules implementing `IAnalysisModule` will have their segment count recorded. Otherwise, the segment count will be treated as 0, resulting in no rows being displayed in the virtual table.
Everything should work the same as before. Only the possibility to use other classes is added.
No follow-ups.
As an author, I have thoroughly tested my changes and carefully followed the instructions in this template

Use the current size in segment store 

---

releng/org.eclipse.tracecompass.integration.core.tests/build.properties
releng/org.eclipse.tracecompass.integration.core.tests/plugin.xml
releng/org.eclipse.tracecompass.integration.core.tests/src/org/eclipse/tracecompass/integration/core/tests/dataproviders/HiddenDataProviderFactory.java
tmf/org.eclipse.tracecompass.tmf.core/schema/org.eclipse.tracecompass.tmf.core.dataprovider.exsd
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/component/DataProviderConstants.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfDataProviderConfigurator.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java
tmf/org.eclipse.tracecompass.tmf.core/templates/dataprovider.ini

Add hideDataProvider element with idRegex and tracetype attributes to
the org.eclipse.tracecompass.tmf.core.dataprovider extension point.
Add dataprovider.ini configuration file template to be stored in the
o.e.tc.tmf.core plug-in state location.
In DataProviderManager methods, filter-out data provider descriptors and
factories that are hidden by the hideDataProvider element, or the
dataprovider.ini configuration file, but that are not shown by the
configuration file. Note that factories cannot be hidden for a specific
trace type.
Define constant DataProviderConstants.CONFIG_SEPARATOR.
Describe use of CONFIG_SEPARATOR in ITmfDataProviderConfigurator's
createDataProviderDescriptors() method.
Add hideDataProvider element in org.eclipse.tracecompass.tmf.core.dataprovider extension to any …

tmf: Add hideDataProvider extension point element

---

rcp/org.eclipse.tracecompass.rcp/feature.xml
releng/org.eclipse.tracecompass.target/tracecompass-e4.20.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.21.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.22.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.23.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.24.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.25.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.26.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.27.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.28.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.29.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.30.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.31.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.33.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.34.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.35.target
releng/org.eclipse.tracecompass.target/tracecompass-e4.36.target
releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target

Add e4.36 and update eStaging targets for 2025-06 M1
Specify fixed version of org.mortbay.jasper.apache-jsp in the target files instead of the RCP feature.xml. Update e4.35 target for this, but not older targets since they have their own legacy version of the RCP feature.xml.
Upgrade trace-event-logger library version to 0.4.1 for all targets.
Build
N/A

releng: Add e4.36 and update eStaging targets for 2025-06 M1

---

releng/org.eclipse.tracecompass.integration.swtbot.tests/src/org/eclipse/tracecompass/integration/swtbot/tests/projectexplorer/ProjectExplorerTracesFolderTest.java
tmf/org.eclipse.tracecompass.tmf.ui.swtbot.tests/src/org/eclipse/tracecompass/tmf/ui/swtbot/tests/views/TimeGraphViewTest.java

The default editor for unrecognized files is now the Generic Editor.
Wait for stable reference image in TimeGraphViewTest.
Build SWTBot tests.
N/A

releng: Fix SWTBot tests for 4.36 platform

---

tmf/org.eclipse.tracecompass.tmf.ui/css/org.eclipse.tracecompass.tmf.ui.dark.css
tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/widgets/timegraph/dialogs/TimeGraphLegend.java

When a new CLabel class is created with Override it stops inheriting Eclipse global theming. Scale also fails to inherit global theming. 
-Open any view containing TimeGraphLegend.java with dark theming enabled 
NA
Theo Dann-Muirhead - theo.dann-muirhead.xd@renesas.com

Fix CLabel and Scale not respecting global themes in TimeGraphLegend

---

tmf/org.eclipse.tracecompass.tmf.analysis.xml.core/src/org/eclipse/tracecompass/internal/tmf/analysis/xml/core/output/XmlDataProviderManager.java

These methods are migrated from the trace server's DataProviderService.
[Added] data provider/descriptor list methods to XmlDataProviderManager
Replace methods in trace-server's DataProviderService with this new API and verify that XML analysis DPs are available as before.

xml: Add data provider/descriptor list methods to XmlDataProviderManager

---

tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java

Exit loop only when match was found when removing data provider.  The code in PR (#254) exited the loop after the first iteration.
fixes #253.
Successful CI.

tmf: Exit loop only when match was found when removing data provider

---

releng/org.eclipse.tracecompass.integration.core.tests/src/org/eclipse/tracecompass/integration/core/tests/dataproviders/DataProviderManagerTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java

Add API DataProviderManager.getAvailableProviders(trace, config). This allows to get all derived data providers created by a configuration.
Successful added unit tests
N/A

tmf: Add API DataProviderManager.getAvailableProviders(trace, config)

---

analysis/org.eclipse.tracecompass.analysis.profiling.ui/src/org/eclipse/tracecompass/internal/analysis/profiling/ui/flamegraph2/FlameGraphView.java
tmf/org.eclipse.tracecompass.tmf.ui/META-INF/MANIFEST.MF

Fix issue #201 by using the context service already used by the timegraphview and the xyview.
1) Open a trace with a call stack analysis
2) Open the flamegraph view
3) Use the keys 'w', 'a', 's', 'd' to move in the view
As the flamegraph view reuses a lot of the timegraph view code. Most of the code for this patch is copied from the timegraph implementation. Refactoring the timegraph view so that it is not coupled to a time based x-axis would fix that issue.

profiling: add wasd controls to flamegraphview

---

rcp/org.eclipse.tracecompass.rcp.product/pom.xml

This warning shows when extracting the RCP on Linux because GNU tar doesn't support that attribute.
The creating time is part of the tarfile name.
Build the RCP and untar the archive on Linux.
See here for details about the setting:
https://tycho.eclipseprojects.io/doc/4.0.10/tycho-p2-director-plugin/archive-products-mojo.html#storeCreationTime
Eclipse platform has it disabled as well.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse-platform-parent/pom.xml

releng: fix unknown extended header keyword 'LIBARCHIVE.creationtime'

---

releng/org.eclipse.tracecompass.integration.core.tests/src/org/eclipse/tracecompass/integration/core/tests/dataproviders/DataProviderManagerTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderFactory.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/ITmfDataProvider.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/tree/ITmfTreeDataProvider.java

This is the first step in having arbitrary data providers. With this PR arbitrary data providers that are not instances of `ITmfTreeDataProvider` can be created by `IDataProviderFactory` implementations and through the `DataProviderManager`. This helps with project such as report and other timeless or non-tree based views.
This PR adds new methods to `IDataProviderFactory` to create provider returning only this new `ITmfDataProvider` interface. It deprecate existing `createProvider` methods in `IDataProviderFactory` in favour of the new interfaces. The default implementations make sure that existing implementations will still work until they are migrated to the new methods.
It also add new methods to fetch and create data providers implementing `ITmfDataProvider` interface to the …

tmf.core: Introduce arbitrary/abstract data provider

---

ctf/org.eclipse.tracecompass.ctf.core/META-INF/MANIFEST.MF
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/event/types/IntegerDeclaration.java
ctf/org.eclipse.tracecompass.tmf.ctf.core/META-INF/MANIFEST.MF
ctf/org.eclipse.tracecompass.tmf.ctf.core/src/org/eclipse/tracecompass/tmf/ctf/core/trace/CtfTmfTrace.java
tmf/org.eclipse.tracecompass.tmf.core/META-INF/MANIFEST.MF
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/component/DataProviderConstants.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/DataProviderManager.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/dataprovider/IDataProviderFactory.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/ITmfDataProvider.java

- Remove deprecated APIs as preparation for 10.0 Trace Compass release. 
- org.eclipse.tracecompass.ctf.core (major version: 5.0.0)
- org.eclipse.tracecompass.tmf.ctf.core (major version: 5.0.0)
- Increment major version org.eclipse.tracecompass.tmf.core to 10.0
- Due to API breakage is reported by API tool due to new ITmfDataProvider parent interface. 
- Update related `@since` and `@Deprecated` annotations and related comments to 10.0. 
All known extensions of ITmfTreeDataProvider still work despite this reported API breakage.
Successful CI. Successful build and execution of incubator features.
N/A

Remove deprecated APIs for 10.0 release

---

tmf/org.eclipse.tracecompass.tmf.analysis.xml.core.tests/src/org/eclipse/tracecompass/tmf/analysis/xml/core/tests/config/XmlConfigurationSourceTest.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/config/ITmfConfigurationSource.java

Use the corresponding methods with ITmfConfiguration instead. Update unit tests for that.
Successful CI.
Remove deprecated API after waiting period.

tmf.config: deprecate create/update methods with parameter map

---

pom.xml
rcp/org.eclipse.tracecompass.rcp/feature.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.35/feature.xml

releng: Build with tracecompass-e4.36 target by default
Build without specifying target. Check 4.36 target is used.
N/A

releng: Build with tracecompass-e4.36 target by default

---

doc/org.eclipse.tracecompass.doc.user/doc/User-Guide.mediawiki
doc/org.eclipse.tracecompass.rcp.doc.user/doc/User-Guide.mediawiki
rcp/org.eclipse.tracecompass.rcp.incubator.ui/plugin.xml
tmf/org.eclipse.tracecompass.tmf/p2.inf

incubator: Point update site to stable-11.0
Build, run and check for updates.
N/A

incubator: Point update site to stable-11.0

---

doc/org.eclipse.tracecompass.doc.dev/doc/Developer-Guide.mediawiki

Remove | from external links in Developer-Guide.mediawiki
Verifiy in preview of the Eclipse's mediawiki editor.
N/A

doc: Remove | from external links in Developer-Guide.mediawiki

---

doc/trace-server/trace-server-dev-guide.md

Minor updates in the trace-server-dev-guide.md
- Fix typos
- Move Utility section to more fitting place
- Fix indentations
Verify in a Markdown editor
N/A

doc: Minor updates in the trace-server-dev-guide.md

---

releng/org.eclipse.tracecompass.target/tracecompass-e4.36.target
releng/org.eclipse.tracecompass.target/tracecompass-eStaging.target

releng: Update e4.36 and eStaging targets for 2025-06 RC2
Build on stable-11.0 branch with e4.36 target.
N/A

releng: Update e4.36 and eStaging targets for 2025-06 RC2

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/model/tree/TmfTreeModelTest.java
tmf/org.eclipse.tracecompass.tmf.core/META-INF/MANIFEST.MF
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/tree/TmfTreeCompositeDataProvider.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/model/tree/TmfTreeModel.java

tmf: Add auto-expand level in TmfTreeModel
The auto-expand level is supposed to be used for the input of the tree. The value 0 means that there is no auto-expand; 1 means that top-level elements are expanded, but not their children; 2 means that top-level elements are expanded, and their children, but not grand-children; and so on.
The value -1 means that all subtrees should be expanded (default).
Contributes to fix https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/801
Run updated unit test.
Related incubator PR.
https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/196
Signed-off-by: Hriday Panchasara <hriday.panchasara@ericsson.com>

Add entry-tree parameter to collapse children

---

analysis/org.eclipse.tracecompass.analysis.os.linux.core/src/org/eclipse/tracecompass/internal/analysis/os/linux/core/resourcesstatus/ResourcesStatusDataProvider.java

Note: The classic Eclipse UI has been doing this in the UI code without that setting (see ResourcesView).
linux: set auto-expand-level in ResourcesStatusDataProvider
Setting the auto-expand-level to 1 of the returned TmfTreeModel when calling fetchTree() will indicate to the clients that only the top-level should be expanded and their children supposed to be collapsed.
With this trace server clients can apply this new setting and it fixes FE issue https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/801.
Run server with this change and run theia-trace-extension change https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1202.
N/A

linux: set auto-expand-level in ResourcesStatusDataProvider

---

DEVELOPMENT_ENV_SETUP.md

It removes an extra backtick that messes up the `literal` formatting.
Look at the rendered version.
None.

Remove extra backtick in dev env setup guide

---

tmf/org.eclipse.tracecompass.tmf.analysis.xml.core/src/org/eclipse/tracecompass/internal/tmf/analysis/xml/core/output/XmlDataProviderManager.java

Fixes duplicate XML driven data providers for experiments with multiple traces of the same type (e.g. LTTng kernel)
Fixes #290 and https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/1204
1. Create experiment with 2 kernel traces
2. Open that experiment
`Futex Content Analysis : Scenario` will be listed for each kernel trace in the AVAILABLE VIEWS view.
N/A

xml: Don't return duplicate data provider descriptors from xml manager

---

tmf/org.eclipse.tracecompass.tmf.core/schema/org.eclipse.linuxtools.tmf.core.tracetype.exsd

Names of
* category
* type
* experiment 
are user-visible string and should have corresponding metadata to help PDE control its values.
PDE doesn't trigger on non-externalized name attribute.
This PR adds "translatable" metadata for `name` attribute to the extension point schema 
After applying this change (and restarting IDE) PDE should recognize mentioned attributes as translatable
(use "Plug-in Tools -> Externalize String" from the project context menu)
I would say that this PR introduces technical debt, it is rather will help to resolve existing one with not translated names.

Mark `name` attributes for `org.eclipse.linuxtools.tmf.core` extension point as translatable

---

ctf/org.eclipse.tracecompass.ctf.core.tests/src/org/eclipse/tracecompass/ctf/core/tests/trace/MetadataPrevalidationTest.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/ctf/core/trace/Metadata.java
ctf/org.eclipse.tracecompass.ctf.core/src/org/eclipse/tracecompass/internal/ctf/core/event/metadata/MetadataStrings.java

Text CTF metadata files are supposed to start with "/* CTF " followed by the CTF version. https://diamon.org/ctf/v1.8.3/#spec7.1
However, to support opening traces that don't comply with the specification check for some common metadata keywords at the beginning of the metadata file when validating the trace. This will allow to open such traces with Trace Compass.
fixes #298
Try to open trace attached in #298 which should work now.

lttng: Make text metadata detection more lenient

---

pom.xml
rcp/org.eclipse.tracecompass.rcp/legacy-e4.36/feature.xml

releng: Build with tracecompass-e4.37 target by default
Build without specifying target. Check 4.37 platform is used.
N/A

releng: Build with tracecompass-e4.37 target by default

---

tmf/org.eclipse.tracecompass.tmf.core.tests/src/org/eclipse/tracecompass/tmf/core/tests/analysis/AnalysisModuleTest.java
tmf/org.eclipse.tracecompass.tmf.core.tests/stubs/org/eclipse/tracecompass/tmf/tests/stubs/analysis/TestAnalysis.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/IAnalysisModule.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/analysis/TmfAbstractAnalysisModule.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/exceptions/TmfAnalysisException.java

tmf: Propagate analysis failure of dependent analysis to parent
fixes #301
Verify using added Junit test
None

tmf: Propagate analysis failure of dependent analysis to parent

---

rcp/org.eclipse.tracecompass.rcp.branding/plugin_customization.ini
rcp/org.eclipse.tracecompass.rcp.product/legacy-e4.23-e4.25/tracing.product
rcp/org.eclipse.tracecompass.rcp.product/legacy-e4.26-e4.29/tracing.product
rcp/org.eclipse.tracecompass.rcp.product/legacy/tracing.product
rcp/org.eclipse.tracecompass.rcp.product/tracing.product

releng: Enable automatic update in the RCP for 11.1 release
Run Eclipse and wait for automatic update.
N/A

releng: Enable automatic update in the RCP for 11.1 release

---

ctf/org.eclipse.tracecompass.tmf.ctf.core/src/org/eclipse/tracecompass/tmf/ctf/core/trace/CtfTmfTrace.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/TmfTrace.java
tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/tmf/core/trace/experiment/TmfExperiment.java

tmf.ctf: Re-initialize start and endtime after transform is applied
With this the start and endtime is correct when opening the experiment that has automatically applied timestamp transformation applied.
fixes #323
Follow steps in #323 and verify that start and end times of both traces in the experiment are correct when listing the experiment from the python client.
Update `TraceManagerService.instantiateTrace()` to not start indexing of trace during experiment creation. The trace will be indexed when experiment is indexed.

tmf.ctf: Re-initialize start and endtime after transform is applied
